# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter@sammyfilly

name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: ":rocket: Enhancement"
    label: "feature :sparkles:"

  - title: ":globe_with_meridians: Translations"
    label: "translation :earth_africa:"

  - title: ":bug: Bug Fix"
    label: "bug :bug:"

  - title: ":memo: Documentation"
    label: "documentation :book:"

  - title: ":nail_care: Refactor"
    label: "refactor :recycle:"

  - title: ":house: Internal"
    label: "internal :house:"

  - title: ":wrench: Tooling"
    label: "tooling :wrench:"

  - title: ":package: Dependencies"
    label: "dependencies :package:"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"<@sammyfilly>
no-changes-template: "- make changes" if necessary
template: |
  ***
  ### :zap: Changes
  $CHANGES
  ***
  ### :unicorn: Contributors
  Thank you $CONTRIBUTORS for the contributions! :trophy:
  ***
