files:
  - source: /src/content/dao/index.md
    dest: /src/content/dao/index.md
    translation: /src/content/dao/%two_letters_code%%original_file_name%
    export_only_approved: true
  - source: /src/content/defi/index.md
    dest: /src/content/defi/index.md
    translation: /src/content/defi/%two_letters_code%%original_file_name%
    export_only_approved: true
  - source: /src/content/nft/index.md
    dest: /src/content/nft/index.md
    translation: /src/content/nft/%two_letters_code%%original_file_name%
    export_only_approved: true
  - source: /src/intl/en/common.json
    dest: "/1) Homepage/common.json"
    translation: /src/intl/%two_letters_code%%original_file_name%
    export_only_approved: true
  - source: /src/intl/en/page-index.json
    dest: "/1) Homepage/page-index.json"
    translation: /src/intl/%two_letters_code%%original_file_name%
    export_only_approved: true
