# .github/workflows/chromatic.yml
name: Chromatic Publish and Testing

on: workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chromatic
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

# List of jobs
jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./package.json
          node-version: 20
      - name: 📥 Install deps
        run: yarn
      - name: Build Storybook
        run: npm run build-storybook
      - name: ⚡ Run chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: fee8e66c9916
          onlyChanged: true
          # 👇 Only fail if Storybook contains stories that error
          exitZeroOnChanges: true
